In [1]:
using POMDPs
using POMDPToolbox
using MCTS
using ParticleFilters
using BasicPOMCP
using FPOMCPOW

include("macrotraffic.jl")
include("jointDTA.jl")
using jointDTA

INFO: Loading HttpServer methods...


HTML{String}("    <script class='js-collapse-script'>\n        var curMatch =\n            window.location.href\n            .match(/(.*?)\\/notebooks\\/.*\\.ipynb/);\n\n        curMatch = curMatch ||\n            window.location.href\n            .match(/(.*?)\\/apps\\/.*\\.ipynb/);\n\n        if ( curMatch ) {\n            \$('head').append('<base href=\"' + curMatch[1] + '/\">');\n        }\n    </script>\n")

HTML{String}("<script class='js-collapse-script' src='/assetserver/6742f1d4bb6b0d11739caa58ab9c3398989375a3-assets/webio/dist/bundle.js'></script>")

HTML{String}("<script class='js-collapse-script' src='/assetserver/6742f1d4bb6b0d11739caa58ab9c3398989375a3-assets/providers/ijulia_setup.js'></script>")

HTML{String}("  <script class='js-collapse-script'>\n    \$('.js-collapse-script').parent('.output_subarea').css('padding', '0');\n  </script>\n")

In [30]:
pomdp = DTAPOMDP(mdp=DTAMDP(lambdas=[0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8], actiondev=2,
joint_action_groups=[[1,2,3], [4,5,6],[7,8],[9,10]],E=4,numagents=10,
elimination_order=[2,3,4,5,1,6,7,9,8,10]),obs_std = 60)

jointDTA.DTAPOMDP
  mdp: jointDTA.DTAMDP
  obs_std: Float64 60.0


In [3]:
pomdp = DTAPOMDP(mdp=DTAMDP(lambdas=[0.8,0.8,0.8,0.8,0.8,0.8],
joint_action_groups=[[1,2],[3,4],[5,6]],E=3,numagents=6,
elimination_order=[2,3,4,5,1,6]),obs_std = 60)

jointDTA.DTAPOMDP
  mdp: jointDTA.DTAMDP
  obs_std: Float64 60.0


In [31]:
actions = generate_actions(pomdp)

1024-element Array{Union{Array{jointDTA.DTAjoint,1}, jointDTA.DTAjoint},1}:
 jointDTA.DTAjoint[jointDTA.DTAjoint(1, 1), jointDTA.DTAjoint(2, 1), jointDTA.DTAjoint(3, 1), jointDTA.DTAjoint(4, 1)]
 jointDTA.DTAjoint[jointDTA.DTAjoint(1, 2), jointDTA.DTAjoint(2, 1), jointDTA.DTAjoint(3, 1), jointDTA.DTAjoint(4, 1)]
 jointDTA.DTAjoint[jointDTA.DTAjoint(1, 3), jointDTA.DTAjoint(2, 1), jointDTA.DTAjoint(3, 1), jointDTA.DTAjoint(4, 1)]
 jointDTA.DTAjoint[jointDTA.DTAjoint(1, 4), jointDTA.DTAjoint(2, 1), jointDTA.DTAjoint(3, 1), jointDTA.DTAjoint(4, 1)]
 jointDTA.DTAjoint[jointDTA.DTAjoint(1, 5), jointDTA.DTAjoint(2, 1), jointDTA.DTAjoint(3, 1), jointDTA.DTAjoint(4, 1)]
 jointDTA.DTAjoint[jointDTA.DTAjoint(1, 6), jointDTA.DTAjoint(2, 1), jointDTA.DTAjoint(3, 1), jointDTA.DTAjoint(4, 1)]
 jointDTA.DTAjoint[jointDTA.DTAjoint(1, 7), jointDTA.DTAjoint(2, 1), jointDTA.DTAjoint(3, 1), jointDTA.DTAjoint(4, 1)]
 jointDTA.DTAjoint[jointDTA.DTAjoint(1, 8), jointDTA.DTAjoint(2, 1), jointDTA.DTAjoint(3, 1

In [32]:
(O, J, G) = generate_orders(pomdp);

In [6]:
O[6]

Dict{Any,Any} with 11 entries:
  Any[2]  => (9, -7)
  Any[1]  => (9, -7)
  Any[11] => (9, -7)
  Any[7]  => (9, -7)
  Any[6]  => (9, -7)
  Any[5]  => (9, -7)
  Any[9]  => (9, -7)
  Any[8]  => (9, -7)
  Any[10] => (9, -7)
  Any[3]  => (9, -7)
  Any[4]  => (9, -7)

In [7]:
J[3]

11-element Array{Any,1}:
 Any[jointDTA.DTAjoint(5, 1)] 
 Any[jointDTA.DTAjoint(5, 2)] 
 Any[jointDTA.DTAjoint(5, 3)] 
 Any[jointDTA.DTAjoint(5, 4)] 
 Any[jointDTA.DTAjoint(5, 5)] 
 Any[jointDTA.DTAjoint(5, 6)] 
 Any[jointDTA.DTAjoint(5, 7)] 
 Any[jointDTA.DTAjoint(5, 8)] 
 Any[jointDTA.DTAjoint(5, 9)] 
 Any[jointDTA.DTAjoint(5, 10)]
 Any[jointDTA.DTAjoint(5, 11)]

In [8]:
G

9-element Array{Array{Int64,1},1}:
 [1, 2] 
 [3, 4] 
 [5, 6] 
 [1]    
 [4]    
 Int64[]
 [6]    
 Int64[]
 Int64[]

In [9]:
d = Tuple([0:10 for i=1:2])
for a in keys(O[1])
    assert(ind2sub(d, a[1].nodeidx)[2] == ind2sub(d, a[2].nodeidx)[1])
    assert(ind2sub(d, a[1].nodeidx)[1] == ind2sub(d, O[1][a][2])[1])
    assert(ind2sub(d, a[2].nodeidx)[2] == ind2sub(d, O[1][a][2])[2])
end
 

LoadError: type Int64 has no field nodeidx

In [10]:
d = Tuple([0:10 for i=1:2])
for a in keys(O[2])
    assert(ind2sub(d, a[1].nodeidx)[2] == O[2][a][2]-1)
end

LoadError: type Int64 has no field nodeidx

In [38]:
h = 1
rng = MersenneTwister(19);
solver = POMCPOWSolver(tree_queries = 10000,
criterion=MaxUCB(20.0),
max_depth=12,
max_time=10.0,
#k_action=20,
enable_action_pw=false,
k_observation=20,
check_repeat_obs=false,
check_repeat_act=false,
rng=rng);
planner = solve(solver, pomdp);
filter = ObsAdaptiveParticleFilter(deepcopy(pomdp), LowVarianceResampler(10), 0.05, MersenneTwister(10));
b = initialize_belief(filter, initial_state_distribution(pomdp))
tree = make_tree(planner, b);
for e = 1:planner.problem.mdp.E
    tree.tried[(h, e)] = Int[]
end
action_space_iter = planner.problem.mdp.joint_actions
for jj in action_space_iter
    for ja in jj
        push_joint_anode!(tree, h, ja,
        init_N(planner.init_N, planner.problem, POWTreeObsNode(tree, h), ja), rand(rng), false)
                            #init_V(planner.init_V, planner.problem, POWTreeObsNode(tree, h), ja),
                            #false)
    end
end

In [39]:
h_node = POWTreeObsNode(tree,1);

In [40]:
MaxUCBflat = MaxUCBjointflat{typeof(actions[1])}(20, actions);
select_best(MaxUCBflat, h_node, rng)

4-element Array{Int64,1}:
  5
 14
 20
 22

In [41]:
MaxUCBVE = MaxUCBjointVE(20,planner.problem.mdp.E, O, J);
select_best(MaxUCBVE, h_node, rng)

4-element Array{Int64,1}:
  5
 14
 20
 22

In [15]:
tree.v[18]+tree.v[210]+tree.v[287]

2.978409959905684

In [16]:
tree.v[120]+tree.v[980]+tree.v[287]

LoadError: BoundsError: attempt to access 363-element Array{Float64,1} at index [980]

In [17]:
tree.tried[(1,2)]

121-element Array{Int64,1}:
 122
 123
 124
 125
 126
 127
 128
 129
 130
 131
 132
 133
 134
   ⋮
 231
 232
 233
 234
 235
 236
 237
 238
 239
 240
 241
 242

In [18]:
zeros(Int, 4)

4-element Array{Int64,1}:
 0
 0
 0
 0